/**
 * Built-in VS Code themes with full color definitions
 * 
 * These themes include UI colors compatible with the app's design system.
 */

import type { VSCodeFullTheme } from '../atoms'

/**
 * S-AGI Dark - Default dark theme matching the app's original design
 * Uses the brand blue (#0034FF) as primary/accent color
 */
const SAGI_DARK: VSCodeFullTheme = {
    id: 'sagi-dark',
    name: 'S-AGI Dark',
    type: 'dark',
    source: 'builtin',
    colors: {
        'editor.background': '#0a0a0a',
        'editor.foreground': '#f4f4f5',
        'foreground': '#f4f4f5',
        'sideBar.background': '#121212',
        'sideBar.foreground': '#f4f4f5',
        'sideBar.border': '#27272a',
        'activityBar.background': '#0a0a0a',
        'activityBar.foreground': '#f4f4f5',
        'panel.background': '#121212',
        'panel.border': '#27272a',
        'tab.activeBackground': '#0a0a0a',
        'tab.inactiveBackground': '#18181b',
        'tab.inactiveForeground': '#a1a1aa',
        'editorGroupHeader.tabsBackground': '#18181b',
        'dropdown.background': '#171717',
        'dropdown.foreground': '#fafafa',
        'input.background': '#121212',
        'input.border': '#27272a',
        'input.foreground': '#f4f4f5',
        'focusBorder': '#0034ff',
        'textLink.foreground': '#0034ff',
        'textLink.activeForeground': '#3366ff',
        'list.activeSelectionBackground': '#27272a',
        'list.hoverBackground': '#18181b',
        'editor.selectionBackground': '#0034ff44',
        'editorLineNumber.foreground': '#52525b',
        'descriptionForeground': '#a1a1aa',
        'errorForeground': '#ef4444',
        'button.background': '#0034ff',
        'button.foreground': '#ffffff',
        'button.secondaryBackground': '#27272a',
        'button.secondaryForeground': '#fafafa',
        'terminal.background': '#0a0a0a',
        'terminal.foreground': '#f4f4f5',
        'terminal.ansiBlack': '#18181b',
        'terminal.ansiRed': '#ef4444',
        'terminal.ansiGreen': '#22c55e',
        'terminal.ansiYellow': '#eab308',
        'terminal.ansiBlue': '#3b82f6',
        'terminal.ansiMagenta': '#a855f7',
        'terminal.ansiCyan': '#06b6d4',
        'terminal.ansiWhite': '#f4f4f5',
    },
}

/**
 * S-AGI Light - Default light theme matching the app's original design
 */
const SAGI_LIGHT: VSCodeFullTheme = {
    id: 'sagi-light',
    name: 'S-AGI Light',
    type: 'light',
    source: 'builtin',
    colors: {
        'editor.background': '#ffffff',
        'editor.foreground': '#0a0a0a',
        'foreground': '#0a0a0a',
        'sideBar.background': '#FAFAFA',
        'sideBar.foreground': '#0a0a0a',
        'sideBar.border': '#e4e4e7',
        'activityBar.background': '#ffffff',
        'activityBar.foreground': '#0a0a0a',
        'panel.background': '#FAFAFA',
        'panel.border': '#e4e4e7',
        'tab.activeBackground': '#ffffff',
        'tab.inactiveBackground': '#f4f4f5',
        'tab.inactiveForeground': '#71717a',
        'editorGroupHeader.tabsBackground': '#f4f4f5',
        'dropdown.background': '#ffffff',
        'dropdown.foreground': '#0a0a0a',
        'input.background': '#FAFAFA',
        'input.border': '#e4e4e7',
        'input.foreground': '#0a0a0a',
        'focusBorder': '#0034ff',
        'textLink.foreground': '#0034ff',
        'textLink.activeForeground': '#0028cc',
        'list.activeSelectionBackground': '#f4f4f5',
        'list.hoverBackground': '#f4f4f5',
        'editor.selectionBackground': '#0034ff33',
        'editorLineNumber.foreground': '#a1a1aa',
        'descriptionForeground': '#71717a',
        'errorForeground': '#dc2626',
        'button.background': '#0034ff',
        'button.foreground': '#ffffff',
        'button.secondaryBackground': '#f4f4f5',
        'button.secondaryForeground': '#18181b',
        'terminal.background': '#fafafa',
        'terminal.foreground': '#0a0a0a',
        'terminal.ansiBlack': '#18181b',
        'terminal.ansiRed': '#dc2626',
        'terminal.ansiGreen': '#16a34a',
        'terminal.ansiYellow': '#ca8a04',
        'terminal.ansiBlue': '#2563eb',
        'terminal.ansiMagenta': '#9333ea',
        'terminal.ansiCyan': '#0891b2',
        'terminal.ansiWhite': '#f4f4f5',
    },
}

/**
 * Cursor Dark theme
 */
const CURSOR_DARK: VSCodeFullTheme = {
    id: 'cursor-dark',
    name: 'Cursor Dark',
    type: 'dark',
    source: 'builtin',
    colors: {
        'editor.background': '#181818',
        'editor.foreground': '#E4E4E4EB',
        'foreground': '#E4E4E4EB',
        'sideBar.background': '#141414',
        'sideBar.foreground': '#E4E4E48D',
        'sideBar.border': '#E4E4E413',
        'activityBar.background': '#141414',
        'activityBar.foreground': '#E4E4E48D',
        'panel.background': '#141414',
        'panel.border': '#E4E4E413',
        'tab.activeBackground': '#181818',
        'tab.inactiveBackground': '#242424',
        'tab.inactiveForeground': '#E4E4E442',
        'editorGroupHeader.tabsBackground': '#141414',
        'dropdown.background': '#181818',
        'dropdown.foreground': '#E4E4E4EB',
        'input.background': '#E4E4E40A',
        'input.border': '#E4E4E413',
        'input.foreground': '#E4E4E4EB',
        'focusBorder': '#E4E4E426',
        'textLink.foreground': '#81A1C1',
        'textLink.activeForeground': '#87A6C4',
        'list.activeSelectionBackground': '#E4E4E41E',
        'list.hoverBackground': '#E4E4E411',
        'editor.selectionBackground': '#40404099',
        'editorLineNumber.foreground': '#E4E4E442',
        'descriptionForeground': '#E4E4E48D',
        'errorForeground': '#E34671',
        'button.background': '#81A1C1',
        'button.foreground': '#191c22',
        'button.secondaryBackground': '#626262',
        'button.secondaryForeground': '#E4E4E4EB',
        'terminal.background': '#141414',
        'terminal.foreground': '#E4E4E4EB',
        'terminal.ansiBlack': '#242424',
        'terminal.ansiRed': '#FC6B83',
        'terminal.ansiGreen': '#3FA266',
        'terminal.ansiYellow': '#D2943E',
        'terminal.ansiBlue': '#81A1C1',
        'terminal.ansiMagenta': '#B48EAD',
        'terminal.ansiCyan': '#88C0D0',
        'terminal.ansiWhite': '#E4E4E4',
    },
}

/**
 * Cursor Light theme
 */
const CURSOR_LIGHT: VSCodeFullTheme = {
    id: 'cursor-light',
    name: 'Cursor Light',
    type: 'light',
    source: 'builtin',
    colors: {
        'editor.background': '#FCFCFC',
        'editor.foreground': '#141414EB',
        'foreground': '#141414EB',
        'sideBar.background': '#F3F3F3',
        'sideBar.foreground': '#141414AD',
        'sideBar.border': '#14141413',
        'activityBar.background': '#F3F3F3',
        'activityBar.foreground': '#141414AD',
        'panel.background': '#F3F3F3',
        'panel.border': '#14141413',
        'tab.activeBackground': '#FCFCFC',
        'tab.inactiveBackground': '#F3F3F3',
        'tab.inactiveForeground': '#141414AD',
        'editorGroupHeader.tabsBackground': '#F3F3F3',
        'dropdown.background': '#FCFCFC',
        'dropdown.foreground': '#141414EB',
        'input.background': '#FCFCFC',
        'input.border': '#14141426',
        'input.foreground': '#141414EB',
        'focusBorder': '#14141426',
        'textLink.foreground': '#3C7CAB',
        'textLink.activeForeground': '#3C7CAB',
        'list.activeSelectionBackground': '#14141411',
        'list.hoverBackground': '#14141411',
        'editor.selectionBackground': '#1414141E',
        'editorLineNumber.foreground': '#1414147A',
        'descriptionForeground': '#141414AD',
        'errorForeground': '#CF2D56',
        'button.background': '#3C7CAB',
        'button.foreground': '#FCFCFC',
        'button.secondaryBackground': '#1414141E',
        'button.secondaryForeground': '#141414EB',
        'terminal.background': '#F3F3F3',
        'terminal.foreground': '#141414EB',
        'terminal.ansiBlack': '#141414EB',
        'terminal.ansiRed': '#CF2D56',
        'terminal.ansiGreen': '#1F8A65',
        'terminal.ansiYellow': '#A16900',
        'terminal.ansiBlue': '#3C7CAB',
        'terminal.ansiMagenta': '#B8448B',
        'terminal.ansiCyan': '#4C7F8C',
        'terminal.ansiWhite': '#FCFCFC',
    },
}

/**
 * Vesper Dark theme
 */
const VESPER_DARK: VSCodeFullTheme = {
    id: 'vesper-dark',
    name: 'Vesper',
    type: 'dark',
    source: 'builtin',
    colors: {
        'editor.background': '#101010',
        'editor.foreground': '#FFFFFF',
        'foreground': '#FFFFFF',
        'sideBar.background': '#101010',
        'sideBar.foreground': '#A0A0A0',
        'sideBar.border': '#232323',
        'activityBar.background': '#101010',
        'activityBar.foreground': '#A0A0A0',
        'panel.background': '#101010',
        'panel.border': '#232323',
        'tab.activeBackground': '#161616',
        'tab.inactiveBackground': '#101010',
        'tab.inactiveForeground': '#505050',
        'editorGroupHeader.tabsBackground': '#101010',
        'dropdown.background': '#161616',
        'dropdown.foreground': '#FFFFFF',
        'input.background': '#1B1B1B',
        'input.border': '#282828',
        'input.foreground': '#FFFFFF',
        'focusBorder': '#FFC799',
        'textLink.foreground': '#FFC799',
        'textLink.activeForeground': '#FFCFA8',
        'list.activeSelectionBackground': '#232323',
        'list.hoverBackground': '#282828',
        'editor.selectionBackground': '#FFFFFF25',
        'editorLineNumber.foreground': '#505050',
        'descriptionForeground': '#A0A0A0',
        'errorForeground': '#FF8080',
        'button.background': '#FFC799',
        'button.foreground': '#000000',
        'button.secondaryBackground': '#232323',
        'button.secondaryForeground': '#FFFFFF',
        'terminal.background': '#101010',
        'terminal.foreground': '#FFFFFF',
        'terminal.ansiBlack': '#1C1C1C',
        'terminal.ansiRed': '#FF8080',
        'terminal.ansiGreen': '#99FFE4',
        'terminal.ansiYellow': '#FFC799',
        'terminal.ansiBlue': '#A0A0A0',
        'terminal.ansiMagenta': '#FFC799',
        'terminal.ansiCyan': '#99FFE4',
        'terminal.ansiWhite': '#FFFFFF',
    },
}

/**
 * Vitesse Dark theme
 */
const VITESSE_DARK: VSCodeFullTheme = {
    id: 'vitesse-dark',
    name: 'Vitesse Dark',
    type: 'dark',
    source: 'builtin',
    colors: {
        'editor.background': '#121212',
        'editor.foreground': '#dbd7ca',
        'foreground': '#dbd7ca',
        'sideBar.background': '#121212',
        'sideBar.foreground': '#dbd7ca',
        'sideBar.border': '#1e1e1e',
        'activityBar.background': '#121212',
        'activityBar.foreground': '#dbd7ca',
        'panel.background': '#121212',
        'panel.border': '#1e1e1e',
        'tab.activeBackground': '#1e1e1e',
        'tab.inactiveBackground': '#121212',
        'tab.inactiveForeground': '#75715e',
        'editorGroupHeader.tabsBackground': '#121212',
        'dropdown.background': '#1e1e1e',
        'dropdown.foreground': '#dbd7ca',
        'input.background': '#1e1e1e',
        'input.border': '#2e2e2e',
        'input.foreground': '#dbd7ca',
        'focusBorder': '#4d9375',
        'textLink.foreground': '#4d9375',
        'textLink.activeForeground': '#5eaab5',
        'list.activeSelectionBackground': '#4d937530',
        'list.hoverBackground': '#1e1e1e',
        'editor.selectionBackground': '#4d937540',
        'editorLineNumber.foreground': '#444444',
        'descriptionForeground': '#75715e',
        'errorForeground': '#cb7676',
        'button.background': '#4d9375',
        'button.foreground': '#121212',
        'button.secondaryBackground': '#2e2e2e',
        'button.secondaryForeground': '#dbd7ca',
        'terminal.background': '#121212',
        'terminal.foreground': '#dbd7ca',
        'terminal.ansiBlack': '#393a34',
        'terminal.ansiRed': '#cb7676',
        'terminal.ansiGreen': '#4d9375',
        'terminal.ansiYellow': '#e6cc77',
        'terminal.ansiBlue': '#6394bf',
        'terminal.ansiMagenta': '#d9739f',
        'terminal.ansiCyan': '#5eaab5',
        'terminal.ansiWhite': '#dbd7ca',
    },
}

/**
 * Vitesse Light theme
 */
const VITESSE_LIGHT: VSCodeFullTheme = {
    id: 'vitesse-light',
    name: 'Vitesse Light',
    type: 'light',
    source: 'builtin',
    colors: {
        'editor.background': '#ffffff',
        'editor.foreground': '#393a34',
        'foreground': '#393a34',
        'sideBar.background': '#fafafa',
        'sideBar.foreground': '#393a34',
        'sideBar.border': '#eeeeee',
        'activityBar.background': '#fafafa',
        'activityBar.foreground': '#393a34',
        'panel.background': '#fafafa',
        'panel.border': '#eeeeee',
        'tab.activeBackground': '#ffffff',
        'tab.inactiveBackground': '#fafafa',
        'tab.inactiveForeground': '#999999',
        'editorGroupHeader.tabsBackground': '#fafafa',
        'dropdown.background': '#ffffff',
        'dropdown.foreground': '#393a34',
        'input.background': '#f5f5f5',
        'input.border': '#eeeeee',
        'input.foreground': '#393a34',
        'focusBorder': '#1e754f',
        'textLink.foreground': '#1e754f',
        'textLink.activeForeground': '#2993a3',
        'list.activeSelectionBackground': '#eeeeee66',
        'list.hoverBackground': '#f5f5f5',
        'editor.selectionBackground': '#22222215',
        'editorLineNumber.foreground': '#aaaaaa',
        'descriptionForeground': '#999999',
        'errorForeground': '#ab5959',
        'button.background': '#1e754f',
        'button.foreground': '#ffffff',
        'button.secondaryBackground': '#eeeeee',
        'button.secondaryForeground': '#393a34',
        'terminal.background': '#fafafa',
        'terminal.foreground': '#393a34',
        'terminal.ansiBlack': '#393a34',
        'terminal.ansiRed': '#ab5959',
        'terminal.ansiGreen': '#1e754f',
        'terminal.ansiYellow': '#a65e2b',
        'terminal.ansiBlue': '#296aa3',
        'terminal.ansiMagenta': '#a13865',
        'terminal.ansiCyan': '#2993a3',
        'terminal.ansiWhite': '#b0b0b0',
    },
}

/**
 * Claude Light theme - Warm, beige tones with orange accent
 */
const CLAUDE_LIGHT: VSCodeFullTheme = {
    id: 'claude-light',
    name: 'Claude Light',
    type: 'light',
    source: 'builtin',
    colors: {
        'editor.background': '#FAF9F5',
        'editor.foreground': '#4a4538',
        'foreground': '#4a4538',
        'sideBar.background': '#FAF9F5',
        'sideBar.foreground': '#4a4538',
        'sideBar.border': '#e5e3de',
        'activityBar.background': '#FAF9F5',
        'activityBar.foreground': '#4a4538',
        'panel.background': '#FAF9F5',
        'panel.border': '#e5e3de',
        'tab.activeBackground': '#FAF9F5',
        'tab.inactiveBackground': '#f5f4f1',
        'tab.inactiveForeground': '#8b8578',
        'editorGroupHeader.tabsBackground': '#f5f4f1',
        'dropdown.background': '#ffffff',
        'dropdown.foreground': '#4a4538',
        'input.background': '#ffffff',
        'input.border': '#d5d3ce',
        'input.foreground': '#4a4538',
        'focusBorder': '#D97857',
        'textLink.foreground': '#D97857',
        'textLink.activeForeground': '#C4684A',
        'list.activeSelectionBackground': '#e8e5dd',
        'list.hoverBackground': '#f0ede7',
        'editor.selectionBackground': '#D9785733',
        'editorLineNumber.foreground': '#a5a193',
        'descriptionForeground': '#8b8578',
        'errorForeground': '#dc2626',
        'button.background': '#D97857',
        'button.foreground': '#ffffff',
        'button.secondaryBackground': '#e8e5dd',
        'button.secondaryForeground': '#4a4538',
        'terminal.background': '#FAF9F5',
        'terminal.foreground': '#4a4538',
        'terminal.ansiBlack': '#4a4538',
        'terminal.ansiRed': '#dc2626',
        'terminal.ansiGreen': '#16a34a',
        'terminal.ansiYellow': '#D97857',
        'terminal.ansiBlue': '#2563eb',
        'terminal.ansiMagenta': '#9333ea',
        'terminal.ansiCyan': '#0891b2',
        'terminal.ansiWhite': '#e5e3de',
    },
}

/**
 * Claude Dark theme - Warm dark tones with orange accent
 */
const CLAUDE_DARK: VSCodeFullTheme = {
    id: 'claude-dark',
    name: 'Claude Dark',
    type: 'dark',
    source: 'builtin',
    colors: {
        'editor.background': '#262624',
        'editor.foreground': '#c9c5bc',
        'foreground': '#c9c5bc',
        'sideBar.background': '#262624',
        'sideBar.foreground': '#c9c5bc',
        'sideBar.border': '#3a3937',
        'activityBar.background': '#262624',
        'activityBar.foreground': '#c9c5bc',
        'panel.background': '#262624',
        'panel.border': '#3d3a36',
        'tab.activeBackground': '#262624',
        'tab.inactiveBackground': '#262624',
        'tab.inactiveForeground': '#8a857c',
        'editorGroupHeader.tabsBackground': '#232120',
        'dropdown.background': '#383633',
        'dropdown.foreground': '#c9c5bc',
        'input.background': '#232120',
        'input.border': '#4a4742',
        'input.foreground': '#c9c5bc',
        'focusBorder': '#D97857',
        'textLink.foreground': '#D97857',
        'textLink.activeForeground': '#E8917A',
        'list.activeSelectionBackground': '#3d3a36',
        'list.hoverBackground': '#353230',
        'editor.selectionBackground': '#D9785744',
        'editorLineNumber.foreground': '#6b6660',
        'descriptionForeground': '#8a857c',
        'errorForeground': '#ef4444',
        'button.background': '#D97857',
        'button.foreground': '#ffffff',
        'button.secondaryBackground': '#3d3a36',
        'button.secondaryForeground': '#c9c5bc',
        'terminal.background': '#262624',
        'terminal.foreground': '#c9c5bc',
        'terminal.ansiBlack': '#232120',
        'terminal.ansiRed': '#ef4444',
        'terminal.ansiGreen': '#22c55e',
        'terminal.ansiYellow': '#D97857',
        'terminal.ansiBlue': '#3b82f6',
        'terminal.ansiMagenta': '#a855f7',
        'terminal.ansiCyan': '#06b6d4',
        'terminal.ansiWhite': '#c9c5bc',
    },
}

/**
 * Min Dark theme
 */
const MIN_DARK: VSCodeFullTheme = {
    id: 'min-dark',
    name: 'Min Dark',
    type: 'dark',
    source: 'builtin',
    colors: {
        'editor.background': '#1f1f1f',
        'editor.foreground': '#d4d4d4',
        'foreground': '#d4d4d4',
        'sideBar.background': '#181818',
        'sideBar.foreground': '#d4d4d4',
        'sideBar.border': '#252525',
        'activityBar.background': '#181818',
        'activityBar.foreground': '#d4d4d4',
        'panel.background': '#1f1f1f',
        'panel.border': '#252525',
        'tab.activeBackground': '#1f1f1f',
        'tab.inactiveBackground': '#181818',
        'tab.inactiveForeground': '#6e6e6e',
        'editorGroupHeader.tabsBackground': '#181818',
        'dropdown.background': '#252525',
        'dropdown.foreground': '#d4d4d4',
        'input.background': '#181818',
        'input.border': '#3c3c3c',
        'input.foreground': '#d4d4d4',
        'focusBorder': '#6ca1ef',
        'textLink.foreground': '#6ca1ef',
        'textLink.activeForeground': '#89b4fa',
        'list.activeSelectionBackground': '#2a2a2a',
        'list.hoverBackground': '#252525',
        'editor.selectionBackground': '#264f78',
        'editorLineNumber.foreground': '#5a5a5a',
        'descriptionForeground': '#6e6e6e',
        'errorForeground': '#f48771',
        'button.background': '#6ca1ef',
        'button.foreground': '#1f1f1f',
        'button.secondaryBackground': '#3c3c3c',
        'button.secondaryForeground': '#d4d4d4',
        'terminal.background': '#1f1f1f',
        'terminal.foreground': '#d4d4d4',
        'terminal.ansiBlack': '#1f1f1f',
        'terminal.ansiRed': '#f48771',
        'terminal.ansiGreen': '#89d185',
        'terminal.ansiYellow': '#e5c07b',
        'terminal.ansiBlue': '#6ca1ef',
        'terminal.ansiMagenta': '#d38aea',
        'terminal.ansiCyan': '#4ec9b0',
        'terminal.ansiWhite': '#d4d4d4',
    },
}

/**
 * Min Light theme
 */
const MIN_LIGHT: VSCodeFullTheme = {
    id: 'min-light',
    name: 'Min Light',
    type: 'light',
    source: 'builtin',
    colors: {
        'editor.background': '#ffffff',
        'editor.foreground': '#1f1f1f',
        'foreground': '#1f1f1f',
        'sideBar.background': '#f3f3f3',
        'sideBar.foreground': '#1f1f1f',
        'sideBar.border': '#e0e0e0',
        'activityBar.background': '#f3f3f3',
        'activityBar.foreground': '#1f1f1f',
        'panel.background': '#f3f3f3',
        'panel.border': '#e0e0e0',
        'tab.activeBackground': '#ffffff',
        'tab.inactiveBackground': '#f3f3f3',
        'tab.inactiveForeground': '#717171',
        'editorGroupHeader.tabsBackground': '#f3f3f3',
        'dropdown.background': '#ffffff',
        'dropdown.foreground': '#1f1f1f',
        'input.background': '#f3f3f3',
        'input.border': '#cecece',
        'input.foreground': '#1f1f1f',
        'focusBorder': '#0451a5',
        'textLink.foreground': '#0451a5',
        'textLink.activeForeground': '#0066cc',
        'list.activeSelectionBackground': '#e8e8e8',
        'list.hoverBackground': '#f3f3f3',
        'editor.selectionBackground': '#add6ff',
        'editorLineNumber.foreground': '#6e7681',
        'descriptionForeground': '#717171',
        'errorForeground': '#d32f2f',
        'button.background': '#0451a5',
        'button.foreground': '#ffffff',
        'button.secondaryBackground': '#e0e0e0',
        'button.secondaryForeground': '#1f1f1f',
        'terminal.background': '#f3f3f3',
        'terminal.foreground': '#1f1f1f',
        'terminal.ansiBlack': '#1f1f1f',
        'terminal.ansiRed': '#cd3131',
        'terminal.ansiGreen': '#14ce14',
        'terminal.ansiYellow': '#949800',
        'terminal.ansiBlue': '#0451a5',
        'terminal.ansiMagenta': '#bc05bc',
        'terminal.ansiCyan': '#0598bc',
        'terminal.ansiWhite': '#a5a5a5',
    },
}

/**
 * All built-in themes
 */
export const BUILTIN_THEMES: VSCodeFullTheme[] = [
    // S-AGI Default themes (first)
    SAGI_DARK,
    SAGI_LIGHT,
    // Cursor themes
    CURSOR_DARK,
    CURSOR_LIGHT,
    // Claude themes
    CLAUDE_DARK,
    CLAUDE_LIGHT,
    // Vesper
    VESPER_DARK,
    // Vitesse
    VITESSE_DARK,
    VITESSE_LIGHT,
    // Min
    MIN_DARK,
    MIN_LIGHT,
]

/**
 * Get theme by ID
 */
export function getBuiltinThemeById(id: string): VSCodeFullTheme | undefined {
    return BUILTIN_THEMES.find((theme) => theme.id === id)
}

/**
 * Get themes by type
 */
export function getBuiltinThemesByType(type: 'light' | 'dark'): VSCodeFullTheme[] {
    return BUILTIN_THEMES.filter((theme) => theme.type === type)
}

/**
 * Default theme IDs for light/dark modes
 */
export const DEFAULT_LIGHT_THEME_ID = 'sagi-light'
export const DEFAULT_DARK_THEME_ID = 'sagi-dark'
