/**
 * Auto-updater module for S-AGI
 *
 * Uses electron-updater to check for and download updates from GitHub Releases.
 * The update manifest files (latest-mac.yml, latest.yml) are generated by
 * electron-builder during the CI/CD build process and uploaded to GitHub Releases.
 *
 * Features:
 * - Differential (delta) downloads via blockmap files
 * - Exponential backoff with jitter on errors
 * - Background download with non-blocking UI notifications
 */

import { autoUpdater, UpdateInfo } from "electron-updater";
import { app, BrowserWindow, ipcMain } from "electron";
import log from "electron-log";

const INITIAL_CHECK_DELAY_MS = 5_000;
const BASE_INTERVAL_MS = 30 * 60 * 1000; // 30 minutes
const MAX_INTERVAL_MS = 4 * 60 * 60 * 1000; // 4 hours cap
const BACKOFF_MULTIPLIER = 2;

// Configure electron-updater logging
autoUpdater.logger = log;
(autoUpdater.logger as typeof log).transports.file.level = "info";

// Download updates automatically once found; ask user before restart.
autoUpdater.autoDownload = true;
autoUpdater.autoInstallOnAppQuit = true;

// Store reference to main window for IPC communication
let mainWindow: BrowserWindow | null = null;
let initialized = false;
let ipcHandlersRegistered = false;
let checkInProgress = false;
let updateDownloaded = false;

// Backoff state
let consecutiveErrors = 0;
let scheduledTimer: ReturnType<typeof setTimeout> | null = null;

/**
 * Initialize the auto-updater
 * @param window - The main BrowserWindow to send update events to
 */
export function initAutoUpdater(window: BrowserWindow): void {
  mainWindow = window;
  window.once("closed", () => {
    if (mainWindow === window) {
      mainWindow = null;
    }
  });

  if (process.mas) {
    log.info("[AutoUpdater] Disabled in Mac App Store builds.");
    return;
  }

  if (initialized) {
    return;
  }
  initialized = true;

  setupAutoUpdaterEvents();
  setupIpcHandlers();
  scheduleNextCheck(INITIAL_CHECK_DELAY_MS);
}

/**
 * Calculate next check delay with exponential backoff and jitter.
 * On success: resets to BASE_INTERVAL_MS.
 * On error: doubles delay each time, capped at MAX_INTERVAL_MS, with random jitter.
 */
function getNextDelay(): number {
  if (consecutiveErrors === 0) {
    return BASE_INTERVAL_MS;
  }

  const exponentialDelay =
    BASE_INTERVAL_MS * Math.pow(BACKOFF_MULTIPLIER, consecutiveErrors);
  const capped = Math.min(exponentialDelay, MAX_INTERVAL_MS);
  // Add random jitter: +-25% of the delay to avoid thundering herd
  const jitter = capped * 0.25 * (Math.random() * 2 - 1);
  const finalDelay = Math.round(capped + jitter);

  log.info(
    `[AutoUpdater] Backoff: ${consecutiveErrors} consecutive errors, next check in ${Math.round(finalDelay / 1000)}s`
  );

  return finalDelay;
}

function scheduleNextCheck(delayMs: number): void {
  if (scheduledTimer) {
    clearTimeout(scheduledTimer);
  }

  scheduledTimer = setTimeout(async () => {
    await checkForUpdates();
    scheduleNextCheck(getNextDelay());
  }, delayMs);
}

/**
 * Check for available updates
 */
export async function checkForUpdates(): Promise<void> {
  if (!initialized) {
    log.warn("[AutoUpdater] checkForUpdates called before initialization");
    return;
  }

  if (checkInProgress) {
    log.info("[AutoUpdater] Check already in progress, skipping.");
    return;
  }

  try {
    checkInProgress = true;
    log.info("[AutoUpdater] Checking for updates...");
    await autoUpdater.checkForUpdates();
    // Success: reset backoff
    consecutiveErrors = 0;
  } catch (error) {
    consecutiveErrors++;
    log.error("[AutoUpdater] Error checking for updates:", error);
    throw error;
  } finally {
    checkInProgress = false;
  }
}

/**
 * Download the available update
 */
export async function downloadUpdate(): Promise<void> {
  if (!initialized) {
    log.warn("[AutoUpdater] downloadUpdate called before initialization");
    return;
  }

  if (updateDownloaded) {
    log.info("[AutoUpdater] Update is already downloaded.");
    return;
  }

  try {
    log.info("[AutoUpdater] Starting download...");
    await autoUpdater.downloadUpdate();
  } catch (error) {
    log.error("[AutoUpdater] Error downloading update:", error);
    throw error;
  }
}

/**
 * Install the downloaded update and restart the app
 */
export function installUpdate(): void {
  log.info("[AutoUpdater] Installing update and restarting...");
  autoUpdater.quitAndInstall(false, true);
}

/**
 * Set up auto-updater event listeners
 */
function setupAutoUpdaterEvents(): void {
  autoUpdater.on("checking-for-update", () => {
    log.info("[AutoUpdater] Checking for update...");
    sendToRenderer("update:checking");
  });

  autoUpdater.on("update-available", (info: UpdateInfo) => {
    updateDownloaded = false;
    consecutiveErrors = 0; // successful contact with server
    log.info("[AutoUpdater] Update available:", info.version);
    sendToRenderer("update:available", {
      version: info.version,
      releaseDate: info.releaseDate,
      releaseNotes: info.releaseNotes,
    });
  });

  autoUpdater.on("update-not-available", (info: UpdateInfo) => {
    updateDownloaded = false;
    consecutiveErrors = 0; // successful contact with server
    log.info("[AutoUpdater] No update available. Current version:", info.version);
    sendToRenderer("update:not-available", { version: info.version });
  });

  autoUpdater.on("download-progress", (progress) => {
    log.info(
      `[AutoUpdater] Download progress: ${progress.percent.toFixed(1)}% (${formatBytes(progress.transferred)}/${formatBytes(progress.total)})`
    );
    sendToRenderer("update:download-progress", {
      percent: progress.percent,
      transferred: progress.transferred,
      total: progress.total,
      bytesPerSecond: progress.bytesPerSecond,
    });
  });

  autoUpdater.on("update-downloaded", (info: UpdateInfo) => {
    updateDownloaded = true;
    log.info("[AutoUpdater] Update downloaded:", info.version);
    sendToRenderer("update:downloaded", {
      version: info.version,
      releaseDate: info.releaseDate,
      releaseNotes: info.releaseNotes,
    });
  });

  autoUpdater.on("error", (error) => {
    log.error("[AutoUpdater] Error:", error);
    sendToRenderer("update:error", { message: getErrorMessage(error) });
  });
}

/**
 * Set up IPC handlers for renderer process communication
 */
function setupIpcHandlers(): void {
  if (ipcHandlersRegistered) {
    return;
  }
  ipcHandlersRegistered = true;

  ipcMain.handle("update:check", async () => {
    try {
      await checkForUpdates();
      return { success: true };
    } catch (error) {
      return { success: false, error: getErrorMessage(error) };
    }
  });

  ipcMain.handle("update:download", async () => {
    try {
      await downloadUpdate();
      return { success: true };
    } catch (error) {
      return { success: false, error: getErrorMessage(error) };
    }
  });

  ipcMain.handle("update:install", () => {
    try {
      installUpdate();
      return { success: true };
    } catch (error) {
      return { success: false, error: getErrorMessage(error) };
    }
  });

  ipcMain.handle("update:get-version", () => {
    return app.getVersion();
  });
}

/**
 * Send event to renderer process
 */
function sendToRenderer(channel: string, data?: unknown): void {
  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.webContents.send(channel, data);
  }
}

function getErrorMessage(error: unknown): string {
  if (error instanceof Error && error.message) {
    return error.message;
  }
  return String(error);
}

/**
 * Format bytes to human readable string
 */
function formatBytes(bytes: number): string {
  if (bytes === 0) return "0 B";
  const k = 1024;
  const sizes = ["B", "KB", "MB", "GB"];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(1)) + " " + sizes[i];
}
